[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "slack-bot"
s3_bucket = "my"
region = "us-east-2"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = [
    
    "AssumedRole=arn:aws:iam::88888888:role/LambdaFullAccess",

]
