AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
 
  env:
    Type: String
  AssumedRole: 
    Type: String

Resources:

  FunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com

  
  FunctionPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      Roles: 
        - !Ref FunctionRole
      PolicyName: CrossAccountAccess
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: 
              - 'sts:AssumeRole'
            Resource : !Ref AssumedRole


  SlackBot:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.6
      Role: !GetAtt FunctionRole.Arn
    
      Environment:
        Variables:
     
          ASSUMED_ROLE: !Ref AssumedRole
         
        
          env: !Ref env
    
